version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      internal:

  evidencia:
    container_name: be-publisher
    restart: always
    image: misko3001/evidencia-be:rabbit-mq
    ports:
      - "8081:8081"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
    networks:
      internal:
    depends_on:
      - keycloak
      - library-db
      - rabbitmq

  evidencia-worker1:
    container_name: be-worker1
    restart: always
    image: misko3001/evidencia-be-worker:1.0
    command:
      - "-worker.name=Worker1"
    ports:
      - "8082:8082"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
    networks:
      internal:
    depends_on:
      - evidencia

  evidencia-worker2:
    container_name: be-worker2
    restart: always
    image: misko3001/evidencia-be-worker:1.0
    command:
      - "-worker.name=Worker2"
    ports:
      - "8083:8083"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
    networks:
      internal:
    depends_on:
      - evidencia

  evidencia-worker3:
    container_name: be-worker3
    restart: always
    image: misko3001/evidencia-be-worker:1.0
    command:
      - "-worker.name=Worker3"
    ports:
      - "8084:8084"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
    networks:
      internal:
    depends_on:
      - evidencia

  library-db:
    container_name: be_postgresql_db
    restart: always
    image: sameersbn/postgresql:10-2
    command:
      - "-p 5433"
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5433:5433"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
    networks:
      internal:

  evidencia-ui:
    container_name: fe_app
    restart: always
    image: misko3001/evidencia-fe:1.0
    ports:
      - "4200:4200"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
    depends_on:
      - keycloak
    networks:
      internal:

  keycloak:
    container_name: keycloak_app
    image: jboss/keycloak:16.1.1
    restart: on-failure
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/tmp/realm-export.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    volumes:
      - ../imports/realm-export.json:/tmp/realm-export.json
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8080:8080"
    networks:
      internal:
    depends_on:
      - keycloak-db

  keycloak-db:
    container_name: keycloak_db
    image: postgres:10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloakdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      internal:

volumes:
  data:
  logs:
  pgdata:

networks:
  internal: